- name: Prepare stuff
  hosts: localhost
  connection: local
  tasks:
    - name: the gang
      become: yes
      apt:
        name: "{{ item }}"
        install_recommends: yes
        state: present
      loop:
        - vim
        - htop
        - curl
        - make
        - build-essential
        - tmux
        - zsh
        - ripgrep
        - fzf
        - fd-find
        - xset
        - xrandr
        - feh
        - i3
        - maim
    - block:
        - name: Changing Default Shell to ZSH
          become: yes
          user:
            name: "{{ ansible_user_id }}"
            shell: /bin/zsh
        - name: get a kitty
          become: yes
          command: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin;
            ln -s ~/.local/kitty.app/bin/kitty /usr/local/bin"
        - name: copy fonts
          command: "cp -r ./.fonts ~/"
        - name: get sweet themes
          become: yes
          shell:
            cmd: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
              $HOME/.oh-my-zsh/custom/themes/powerlevel10k"
        - name: Get that nvm boy
          become: yes
          command: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh
            | bash; nvm install --lts"
        - name: get my boi cargo
          become: yes
          command: "curl https://sh.rustup.rs -sSf | sh"
        - name: Tree sitter fam
          command: "cargo install tree-sitter-cli"
        - name: Neovim
          become: yes
          command: "curl -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
            -o nvim; mv nvim /usr/local/bin"
        - name: Packer
          command: "git clone --depth 1 https://github.com/wbthomason/packer.nvim
            ~/.local/share/nvim/site/pack/packer/start/packer.nvim"
        - name: Copy dotfiles
          become: yes
          shell: cp {{ item }} ~/
          with_files:
            - .zshrc
            - .zshenv
            - .tmux.conf
            - .bashrc
        - name: copy bg
          command: cp -r ./bg ~/
        - name: copy .config
          command: mkdir -p ~/.config; cp -r ./.config/* ~/.config
    - block:
        - name: "Get golang"
          get_url:
            url: https://go.dev/dl/go1.20.linux-amd64.tar.gz
            dest: "./go.tar.gz"
            register: godownload
        - name: "Install golang"
          become: yes
          command: rm -rf /usr/local/go && tar -C /usr/local -xzf go.tar.gz
          when: godownload.rc == 0
