- name: Prepare stuff
  hosts: localhost
  connection: local
  tasks: 
    - name: Copy dotfiles
      shell: cp {{ item }} ~/
      loop:
        - ../.zshrc
        - ../.zshenv
        - ../.tmux.conf
        - ../.bashrc
    - name: copy .config stuff
      shell:
        cmd: "cp -r ../.config/* ~/.config/"
