- name: Prepare stuff
  hosts: localhost
  connection: local
  tasks:
    - name: Install latest i3 for Ubuntu
      block: 
        - name: Install keyring deb
          become: yes
          become_user: root
          apt: 
            deb: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2022.02.17_all.deb
        - name: get dist name
          shell:
            cmd: echo $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=)
          register: distname
        - name: Add i3 repo
          become: yes
          become_user: root
          apt_repository:
            repo: deb http://debian.sur5r.net/i3/ {{ distname.stdout }} universe
        - name: Install i3
          become: yes
          become_user: root
          apt:
            name: i3
            update_cache: true
