- name: Setup Kitty
  hosts: localhost
  connection: local
  tasks:
    - name: remove old kitty
      file:
        state: "absent"
        path: "~/.local/kitty.app"
    - name: get a new kitty
      get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: "./kitty-installer.sh"
    - name: install new kitty
      command: /bin/sh "./kitty-installer.sh"
    - name: Link new Kitty
      file:
        src: "~/.local/kitty.app/bin/kitty"
        dest: "~/.local/bin/kitty"
        state: link
    - name: remove new kitty intaller
      file:
        state: "absent"
        path: "./kitty-installer.sh"
