- name: Picom Setup
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
    - name: Install Picom deps
      become: yes
      dnf:
        name:
          - dbus-devel
          - gcc
          - git
          - ninja-build
          - libconfig-devel
          - libdrm-devel
          - libev-devel
          - libX11-devel
          - libX11-xcb
          - libXext-devel
          - libxcb-devel
          - libGL-devel
          - libEGL-devel
          - meson
          - pcre2-devel
          - pixman-devel
          - uthash-devel
          - xcb-util-image-devel
          - xcb-util-renderutil-devel
          - xorg-x11-proto-devel
      when: ansible_facts['distribution'] == "Fedora"

    - name: Install Picom deps
      become: yes
      apt:
        name:
          - libxext-dev 
          - libxcb1-dev 
          - libxcb-damage0-dev 
          - libxcb-dpms0-dev 
          - libxcb-xfixes0-dev 
          - libxcb-shape0-dev 
          - libxcb-render-util0-dev 
          - libxcb-render0-dev 
          - libxcb-randr0-dev 
          - libxcb-composite0-dev 
          - libxcb-image0-dev 
          - libxcb-present-dev 
          - libxcb-glx0-dev 
          - libpixman-1-dev 
          - libdbus-1-dev 
          - libconfig-dev 
          - libgl-dev 
          - libegl-dev 
          - libpcre2-dev 
          - libevdev-dev 
          - uthash-dev 
          - libev-dev 
          - libx11-xcb-dev 
          - meson
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Clone picom repo
      git:
        repo: https://github.com/yshui/picom
        dest: ./picom
        recursive: yes
        update: yes
    - name: Build and Install picom
      become: yes
      shell: "cd ./picom; meson setup --buildtype=release . build && ninja -C build
        install"
    - name: Remove picom git
      become: yes
      file:
        state: "absent"
        path: "./picom"
