- name: Prepare stuff
  hosts: localhost
  connection: local
  tasks:
    - name: Get discord tar
      unarchive:
        src: https://discord.com/api/download/stable?platform=linux&format=tar.gz
        dest: "~/.local/"
        remote_src: yes

    - name: remove old discord files
      file:
        path: "~/.local/Discord"
        state: "absent"

    - name: Link to bin
      file:
        src: "~/.local/Discord/Discord"
        dest: "~/.local/bin/discord"
        state: link
